### ISSUE TITLE
mac上按照文档的打包方法，运行Electron，根本无法运行啊

### ISSUE THREAD

**Issue by jmolboy** [wq123456/cnode-electron#1]
没有asar文件，使用electron能直接打开手动添加的app目录？

**Comment by jmolboy** [comment]
已从度盘下载查看了下，也配置了electron的info.plist，感觉文档写的发布方式太粗糙了；

**Comment by jmolboy** [comment]
但是这个项目的确是我学习electron的好案例，赞一个！

**Comment by hanxie-crypto** [comment]
其实这边打包很简单，就是从electron-prebuilt dist里面 Electron 这个执行文件中假如你自己的内容，你先测试下这个能不能打开

At 2016-05-06 11:18:20, "jmolboy" notifications@github.com wrote:

Closed #1.
