### ISSUE TITLE
你说官方的asar方法打包限制太多，有没有好的打包方法，尤其是打包成windows下可执行文件

### ISSUE THREAD

**Issue by panzt** [wq123456/cnode-electron#2]
你说官方的asar方法打包限制太多，有没有好的打包方法，尤其是打包成windows下可执行文件

**Comment by hanxie-crypto** [comment]
有个简单的办法
https://github.com/electron/electron/releases/tag/v1.3.3 https://github.com/electron/electron/releases/tag/v1.3.3
你登录这个发布版网址
找到你想要发布的平台的demo 比如你想搞windows版本的
就下
electron-v1.3.3-darwin-x64.zip https://github.com/electron/electron/releases/download/v1.3.3/electron-v1.3.3-darwin-x64.zip
然后解压里面有resources文件夹
你在这里面创建一个叫app的文件夹，如果里面有可以删掉
然后把自己项目的依赖放进去就可以，比如你用到任何的字体文件声音文件css之类的以及node_module都放进去。保存后应该就打开外面的exe文件，应该就可以看到自己的东西，然后再借助其他工具改改图标，名称之类的
不过这种方式会暴露你的源文件，所以建议可以把代码混淆压缩，重要信息加密。然后应该有更严密的打包方法，不过我最近没时间研究这方面，以后大家一起去找找再互相交流一下心得拜。

**Comment by panzt** [comment]
很有用，感谢

**Comment by daiyunchao** [comment]
@wq123456  为啥我下载的electron-v1.3.3-darwin-x64.zip 文件夹下没有resources文件夹 而且也没有exe的执行文件

**Comment by daiyunchao** [comment]
@wq123456 
目录结构是:
Electron.app
LICENSE
LICENSES.chromium.html
version
在Electron.app 里面有很多文件

**Comment by daiyunchao** [comment]
@wq123456 
我在electron-xxxx-win32-x64.zip里面找到了对应的文件
是否写错了?
