### ISSUE TITLE
看你的代码，程序的后端应该是用Restful的API方式写的吧，有没有遇到什么坑，分享一下呗

### ISSUE THREAD

**Issue by panzt** [wq123456/cnode-electron#3]
看你的代码，程序的后端应该是用Restful的API方式写的吧，有没有遇到什么坑，分享一下呗

**Comment by hanxie-crypto** [comment]
服务端是来源的啊，node中文社区，可以去看看人家写的

发自我的 iPhone

**Comment by panzt** [comment]
看到了，是node中文社区开放出来的api
我最近一个项目需要用后端语言写一个Restful的交互接口和前端的React和Antd进行交互，压力山大啊
